"use client";
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'ASX',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html className='myTheme bg-white'>
      <body>
        <SessionProvider>
          <Navigation />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
