import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ASX',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='myTheme bg-white'>
      <body>

        <Navigation />
        {children}
      </body>
    </html>
  )
}
